[package]
name = "web_server_web-guessing_game_1"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4.9.0"
fastrand= "2.3.0"
tokio={version="1.43.0", features=["macros", "rt-multi-thread"]} 